name: test_mobdev
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/image/logo.png
    - assets/svg/animasi-1.svg
    - assets/svg/animasi-2.svg
    - assets/svg/animasi-3.svg
    - assets/svg/icon-courses.svg
    - assets/svg/icon-lesson.svg
